spring:
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true