CREATE TABLE kspo_fitness_measurement
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_sequence_value         VARCHAR(100) NOT NULL,
    measurement_sequence_no       INTEGER      NOT NULL,
    center_name                   VARCHAR(100) NOT NULL,
    age_group_name                VARCHAR(30)  NOT NULL,
    measurement_place_type_name   VARCHAR(30)  NOT NULL,
    measurement_age               INTEGER      NOT NULL,
    input_type_name               VARCHAR(30)  NOT NULL,
    certification_grade_name      VARCHAR(30),
    measurement_date              DATE         NOT NULL,
    gender_code                   VARCHAR(1)    NOT NULL,
    measurement_item_019_value    NUMERIC(20, 6),
    measurement_item_023_value    NUMERIC(20, 6),
    movement_prescription_content TEXT,
    imported_at                   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kspo_fitness_measurement_source
        UNIQUE (member_sequence_value, measurement_sequence_no, measurement_date)
);

CREATE INDEX idx_kspo_fitness_measurement_demographic
    ON kspo_fitness_measurement (measurement_age, gender_code, measurement_date);

CREATE INDEX idx_kspo_fitness_measurement_grade
    ON kspo_fitness_measurement (certification_grade_name);
