CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE kspo_exercise_prescription
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_hash         VARCHAR(32)  NOT NULL UNIQUE,
    prescription_content TEXT         NOT NULL,
    embedding            VECTOR(1536),
    embedding_model      VARCHAR(100),
    embedded_at          TIMESTAMP,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kspo_exercise_prescription_audience
(
    prescription_id      BIGINT      NOT NULL,
    gender_code          VARCHAR(1)  NOT NULL,
    measurement_age      INTEGER     NOT NULL,
    certification_grade  VARCHAR(30) NOT NULL DEFAULT '',
    source_count          INTEGER     NOT NULL,
    PRIMARY KEY (prescription_id, gender_code, measurement_age, certification_grade),
    CONSTRAINT fk_kspo_prescription_audience_prescription
        FOREIGN KEY (prescription_id)
            REFERENCES kspo_exercise_prescription (id)
            ON DELETE CASCADE
);

INSERT INTO kspo_exercise_prescription (content_hash, prescription_content)
SELECT md5(movement_prescription_content), movement_prescription_content
FROM kspo_fitness_measurement
WHERE movement_prescription_content IS NOT NULL
  AND btrim(movement_prescription_content) <> ''
GROUP BY md5(movement_prescription_content), movement_prescription_content
ON CONFLICT (content_hash) DO NOTHING;

INSERT INTO kspo_exercise_prescription_audience (
    prescription_id,
    gender_code,
    measurement_age,
    certification_grade,
    source_count
)
SELECT
    prescription.id,
    measurement.gender_code,
    measurement.measurement_age,
    COALESCE(measurement.certification_grade_name, ''),
    COUNT(*)
FROM kspo_fitness_measurement measurement
JOIN kspo_exercise_prescription prescription
  ON prescription.content_hash = md5(measurement.movement_prescription_content)
WHERE measurement.movement_prescription_content IS NOT NULL
  AND btrim(measurement.movement_prescription_content) <> ''
GROUP BY
    prescription.id,
    measurement.gender_code,
    measurement.measurement_age,
    COALESCE(measurement.certification_grade_name, '')
ON CONFLICT (prescription_id, gender_code, measurement_age, certification_grade)
DO UPDATE SET source_count = EXCLUDED.source_count;

CREATE INDEX idx_kspo_prescription_audience_demographic
    ON kspo_exercise_prescription_audience (gender_code, measurement_age);

CREATE INDEX idx_kspo_prescription_embedding_cosine
    ON kspo_exercise_prescription
    USING hnsw (embedding vector_cosine_ops)
    WHERE embedding IS NOT NULL;
