CREATE TABLE fitple_exercise_standard
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_type    VARCHAR(30)    NOT NULL,
    gender           VARCHAR(10)    NOT NULL,
    minimum_age      INTEGER        NOT NULL,
    maximum_age      INTEGER        NOT NULL,
    average_value    NUMERIC(10, 2) NOT NULL,
    measurement_type VARCHAR(30)    NOT NULL,
    protocol         VARCHAR(100)   NOT NULL,
    version          VARCHAR(30)    NOT NULL,
    is_active        BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_fitple_exercise_standard_age
        CHECK (minimum_age >= 0 AND maximum_age >= minimum_age),
    CONSTRAINT ck_fitple_exercise_standard_type
        CHECK (exercise_type IN ('PUSH_UP', 'PLANK')),
    CONSTRAINT uk_fitple_exercise_standard_version
        UNIQUE (exercise_type, gender, minimum_age, maximum_age, version)
);

INSERT INTO fitple_exercise_standard (
    exercise_type, gender, minimum_age, maximum_age, average_value,
    measurement_type, protocol, version, is_active
)
VALUES
    ('PUSH_UP', 'MALE',   10, 19,  13, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 10, 19,   7, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   10, 19,  83, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 10, 19,  68, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),

    ('PUSH_UP', 'MALE',   20, 29,  22, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 20, 29,  16, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   20, 29, 105, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 20, 29,  90, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),

    ('PUSH_UP', 'MALE',   30, 39,  20, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 30, 39,  14, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   30, 39,  95, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 30, 39,  85, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),

    ('PUSH_UP', 'MALE',   40, 49,  16, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 40, 49,  12, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   40, 49,  85, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 40, 49,  75, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),

    ('PUSH_UP', 'MALE',   50, 59,  12, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 50, 59,   9, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   50, 59,  70, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 50, 59,  62, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),

    ('PUSH_UP', 'MALE',   60, 69,  10, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 60, 69,   7, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   60, 69,  55, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 60, 69,  48, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),

    ('PUSH_UP', 'MALE',   70, 150,  7, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PUSH_UP', 'FEMALE', 70, 150,  5, 'REPETITION',    'MAX_VALID_REPETITIONS_IN_60_SECONDS', 'FITPLE_V1', TRUE),
    ('PLANK',   'MALE',   70, 150, 40, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE),
    ('PLANK',   'FEMALE', 70, 150, 35, 'VALID_DURATION', 'MAX_VALID_HOLD_SECONDS',              'FITPLE_V1', TRUE);
