CREATE TABLE measurement_insight
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                      BIGINT       NOT NULL,
    measurement_group_id         VARCHAR(36)  NOT NULL,
    comparisons_json             TEXT         NOT NULL,
    insights_json                TEXT         NOT NULL,
    reference_prescriptions_json TEXT         NOT NULL,
    created_at                   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_measurement_insight_group UNIQUE (measurement_group_id)
);

CREATE INDEX idx_measurement_insight_user ON measurement_insight (user_id);
